openapi: 3.2.0
info:
  title: wazo Provd API
  description: Provisioning application REST API
  version: '0.2'
  contact:
    name: Wazo Dev Team
    url: https://wazo-platform.org/
    email: dev@wazo.community
  x-logo:
    url: https://wazo-platform.org/images/logo-black.svg
    backgroundColor: '#FAFAFA'
    altText: Wazo Logo
servers:
- url: /api/provd/0.2
security:
- wazo_auth_token: []
tags:
- name: provd
paths:
  /:
    get:
      summary: Get the Provd Manager resource
      description: '**Required ACL:** `provd.read`


        The provd manager resource represents the main entry point to the wazo-provd REST API'
      tags:
      - provd
      responses:
        '200':
          description: OK
          content:
            application/vnd.proformatique.provd+json:
              schema:
                $ref: '#/components/schemas/LinksObject'
      operationId: getRoot
      x-operation-id-source: derived
  /configure:
    get:
      summary: Get the general provd configuration
      description: '**Required ACL:** `provd.configure.read`'
      tags:
      - provd
      responses:
        '200':
          description: OK
          content:
            application/vnd.proformatique.provd+json:
              schema:
                $ref: '#/components/schemas/GeneralConfigsObject'
      operationId: getConfigure
      x-operation-id-source: derived
  /configure/{param_id}:
    get:
      summary: Get the configuration parameter value
      description: '''**Required ACL:** `provd.configure.{param_id}.read`''


        Wazo-Tenant header is only valid for `provisioning_key`'
      tags:
      - provd
      parameters:
      - $ref: '#/components/parameters/ParamId'
      - $ref: '#/components/parameters/TenantUUID'
      responses:
        '200':
          description: OK
          content:
            application/vnd.proformatique.provd+json:
              schema:
                $ref: '#/components/schemas/Param'
        '404':
          $ref: '#/components/responses/NoSuchResourceError'
      operationId: getConfigureByParamId
      x-operation-id-source: derived
    put:
      summary: Set the value of a parameter
      description: '**Required ACL:** `provd.configure.{param_id}.update`'
      tags:
      - provd
      parameters:
      - $ref: '#/components/parameters/ParamId'
      - $ref: '#/components/parameters/ParamBody'
      responses:
        '204':
          $ref: '#/components/responses/NoContentResponse'
        '404':
          $ref: '#/components/responses/NoSuchResourceError'
        '415':
          $ref: '#/components/responses/UnsupportedMediaError'
      operationId: putConfigureByParamId
      x-operation-id-source: derived
  /configure/plugin_server:
    put:
      summary: Update the configuration's plugin_server
      description: '**Required ACL:** `provd.configure.plugin_server.update`'
      tags:
      - provd
      responses:
        '204':
          $ref: '#/components/responses/NoContentResponse'
        '404':
          $ref: '#/components/responses/NoSuchResourceError'
        '415':
          $ref: '#/components/responses/UnsupportedMediaError'
      requestBody:
        content:
          application/vnd.proformatique.provd+json:
            schema:
              $ref: '#/components/schemas/PluginServer'
        description: Configuration parameter body definition
      operationId: putConfigurePluginServer
      x-operation-id-source: derived
  /configure/http_proxy:
    put:
      summary: Update the configuration's http_proxy
      description: '**Required ACL:** `provd.configure.http_proxy.update`'
      tags:
      - provd
      responses:
        '204':
          $ref: '#/components/responses/NoContentResponse'
        '404':
          $ref: '#/components/responses/NoSuchResourceError'
        '415':
          $ref: '#/components/responses/UnsupportedMediaError'
      requestBody:
        content:
          application/vnd.proformatique.provd+json:
            schema:
              $ref: '#/components/schemas/HttpProxy'
        description: Configuration parameter body definition
      operationId: putConfigureHttpProxy
      x-operation-id-source: derived
  /configure/https_proxy:
    put:
      summary: Update the configuration's https_proxy
      description: '**Required ACL:** `provd.configure.https_proxy.update`'
      tags:
      - provd
      responses:
        '204':
          $ref: '#/components/responses/NoContentResponse'
        '404':
          $ref: '#/components/responses/NoSuchResourceError'
        '415':
          $ref: '#/components/responses/UnsupportedMediaError'
      requestBody:
        content:
          application/vnd.proformatique.provd+json:
            schema:
              $ref: '#/components/schemas/HttpsProxy'
        description: Configuration parameter body definition
      operationId: putConfigureHttpsProxy
      x-operation-id-source: derived
  /configure/ftp_proxy:
    put:
      summary: Update the configuration's ftp_proxy
      description: '**Required ACL:** `provd.configure.ftp_proxy.update`'
      tags:
      - provd
      responses:
        '204':
          $ref: '#/components/responses/NoContentResponse'
        '404':
          $ref: '#/components/responses/NoSuchResourceError'
        '415':
          $ref: '#/components/responses/UnsupportedMediaError'
      requestBody:
        content:
          application/vnd.proformatique.provd+json:
            schema:
              $ref: '#/components/schemas/FtpProxy'
        description: Configuration parameter body definition
      operationId: putConfigureFtpProxy
      x-operation-id-source: derived
  /configure/locale:
    put:
      summary: Update the configuration's locale
      description: '**Required ACL:** `provd.configure.locale.update`'
      tags:
      - provd
      responses:
        '204':
          $ref: '#/components/responses/NoContentResponse'
        '404':
          $ref: '#/components/responses/NoSuchResourceError'
        '415':
          $ref: '#/components/responses/UnsupportedMediaError'
      requestBody:
        content:
          application/vnd.proformatique.provd+json:
            schema:
              $ref: '#/components/schemas/Locale'
        description: Configuration parameter body definition
      operationId: putConfigureLocale
      x-operation-id-source: derived
  /configure/NAT:
    put:
      summary: Update the configuration's NAT
      description: '**Required ACL:** `provd.configure.nat.update`'
      tags:
      - provd
      responses:
        '204':
          $ref: '#/components/responses/NoContentResponse'
        '404':
          $ref: '#/components/responses/NoSuchResourceError'
        '415':
          $ref: '#/components/responses/UnsupportedMediaError'
      requestBody:
        content:
          application/vnd.proformatique.provd+json:
            schema:
              $ref: '#/components/schemas/Nat'
        description: Configuration parameter body definition
      operationId: putConfigureNAT
      x-operation-id-source: derived
  /configure/provisioning_key:
    put:
      summary: Update the tenant provisioning key
      description: '**Required ACL:** `provd.configure.{tenant_uuid}.provisioning_key.update`'
      tags:
      - provd
      parameters:
      - $ref: '#/components/parameters/TenantUUID'
      responses:
        '204':
          $ref: '#/components/responses/NoContentResponse'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '404':
          $ref: '#/components/responses/NoSuchResourceError'
        '415':
          $ref: '#/components/responses/UnsupportedMediaError'
      requestBody:
        content:
          application/vnd.proformatique.provd+json:
            schema:
              $ref: '#/components/schemas/ProvisioningKey'
        description: Configuration parameter body definition
      operationId: putConfigureProvisioningKey
      x-operation-id-source: derived
components:
  schemas:
    Param:
      description: A configuration parameter
      properties:
        param:
          $ref: '#/components/schemas/ParamObject'
      example:
        param:
          value: http://provd.wazo.community/plugins/2/stable
    GeneralConfigObject:
      properties:
        description:
          type: string
        id:
          type: string
        links:
          $ref: '#/components/schemas/LinksObject'
        value:
          type: string
    HttpsProxy:
      title: HTTPS proxy configuration
      properties:
        param:
          type: string
          description: The proxy for HTTPS requests. Format is `host:port`
      example:
        param:
          value: example.com:8081
    ParamObject:
      properties:
        value:
          type: string
    LinksObject:
      description: Links object
      type: object
      properties:
        links:
          type: array
          description: Links to different resources
          items:
            $ref: '#/components/schemas/LinkObject'
    HttpProxy:
      title: HTTP proxy configuration
      properties:
        param:
          type: string
          description: The proxy for HTTP requests. Format is `http://[user:password@]host:port`
      example:
        param:
          value: http://root:secret@example.com:8080
    Nat:
      title: NAT configuration
      properties:
        param:
          type: string
          description: Set to `1` if all the devices are behind a NAT
      example:
        param:
          value: '1'
    GeneralConfigsObject:
      properties:
        params:
          type: array
          items:
            $ref: '#/components/schemas/GeneralConfigObject'
    ProvisioningKey:
      description: Provisioning Key configuration
      properties:
        param:
          type: string
          description: Provisioning key used to authenticate request to fetch provisioning configuration file
      example:
        param:
          value: a1b2c3d4e5f6g7h8
    PluginServer:
      title: Plugin server configuration
      properties:
        param:
          type: string
          description: The plugins repository URL
      example:
        param:
          value: http://provd.wazo.community/plugins/2/stable/
    ErrorMessage:
      description: Error message response
      type: string
    Locale:
      title: Locale configuration
      properties:
        param:
          type: string
          description: 'The current locale. For example: `en_US`'
      example:
        param:
          value: en_US
    FtpProxy:
      title: FTP proxy configuration
      properties:
        param:
          type: string
          description: The proxy for FTP requests. Format is `http://[user:password@]host:port`
      example:
        param:
          value: http://root:secret@example.com:8082
    LinkObject:
      description: Link Object
      type: object
      properties:
        href:
          type: string
          description: Location of the resource
        rel:
          type: string
          description: Relation to the resource
  responses:
    NoContentResponse:
      description: No content
    UnsupportedMediaError:
      description: Unsupported media type. This error occurs if you forgot to include the Content-Type header
      content:
        application/vnd.proformatique.provd+json:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
    NoSuchResourceError:
      description: No such resource. The provided id does not exist
      content:
        application/vnd.proformatique.provd+json:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
    BadRequestError:
      description: Bad request. The device ID, IP or MAC may be invalid
      content:
        application/vnd.proformatique.provd+json:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
  parameters:
    TenantUUID:
      name: Wazo-Tenant
      in: header
      description: The tenant's UUID, defining the ownership of a given resource
      schema:
        type: string
    ParamId:
      required: true
      name: param_id
      in: path
      description: Configuration parameter ID
      schema:
        type: string
    ParamBody:
      description: Configuration parameter body definition
      name: body
      in: body
      schema:
        $ref: '#/components/schemas/Param'
  securitySchemes:
    wazo_auth_token:
      type: apiKey
      name: X-Auth-Token
      in: header
x-xivo-name: provd
x-xivo-port: 8666
